#!/bin/bash
# rsync backup util

function backup_internal ()
{
   sudo bash -c "mkdir /mnt/backup"
   sudo bash -c "mount /dev/nvme0n1p3 /mnt/backup/"

   if [[ $? -ne 0 ]] ; then
      echo -e "--> Mount failed."
      exit 1
   fi

   sudo rsync -a -P --delete \
      /home/aurelius/{Apps,bin,build,Documents,Picutres,wiki} \
   /mnt/backup/aurelius/

   sync ; sync ; sync

   sudo rsync -a -P --delete \
      /home/aurelius/.task \
      /home/aurelius/.vim \
         --exclude="view" \
      /home/aurelius/.bashrc \
      /home/aurelius/.taskrc \
      /home/aurelius/.tmux.conf \
      /home/aurelius/.vimrc \
   /mnt/backup/dotfiles/

   sync ; sync ; sync

   sudo bash -c "umount /dev/nvme0n1p3"
   sudo bash -c "rmdir /mnt/backup"
}


function backup_ssh ()
{
   rsync -a -P --delete -e ssh \
      /home/aurelius/{Apps,bin,build,Documents,Picutres,wiki} \
   senatus:/media/backup/populus/aurelius/

   rsync -aLK --progress -e ssh \
      /home/aurelius/.config \
      /home/aurelius/.task \
      /home/aurelius/.vim \
         --exclude="view" \
      /home/aurelius/.bashrc \
      /home/aurelius/.taskrc \
      /home/aurelius/.tmux.conf \
      /home/aurelius/.vimrc \
   senatus:/media/backup/populus/dotfiles/
}


case $1 in
   -i | --internal )
      backup_internal ;;

   -s | --ssh )
      backup_ssh ;;

   *) echo -e "--> Select option from (-i)nternal (-s)sh"
      exit 1 ;;
esac
