#!/bin/bash
# rsync backup util

rd="\033[31m"
br="\033[37;1m"
rs="\033[0m"


function backup_internal ()
{
   sudo bash -c "mkdir /mnt/backup"
   sudo bash -c "mount /dev/nvme0n1p3 /mnt/backup/"

   if [[ $? -ne 0 ]] ; then
      printf "${rd}◆${rs} Mount failed."
      exit 1
   fi

   sudo rsync -a -P --delete \
      /home/aurelius/{Apps,bin,build,Documents,Pictures,wiki} \
      /mnt/backup/aurelius/

   sync ; sync ; sync

   sudo rsync -a -P --delete \
      --exclude "view/" \
      /home/aurelius/.task \
      /home/aurelius/.vim \
      /home/aurelius/.bashrc \
      /home/aurelius/.taskrc \
      /home/aurelius/.tmux.conf \
      /home/aurelius/.vimrc \
      /mnt/backup/dotfiles/

   sync ; sync ; sync

   sudo bash -c "umount /dev/nvme0n1p3"
   sudo bash -c "rmdir /mnt/backup"
}


function backup_ssh ()
{
   rsync -a -P --delete -e ssh \
      /home/aurelius/{Apps,bin,build,Documents,Pictures,wiki} \
      senatus:/tidepool/backup/aurelius/populus/aurelius/

   rsync -aLKP --delete \
      --exclude "view/" \
      --exclude "undodir/" \
      -e ssh \
         /home/aurelius/.task \
         /home/aurelius/.vim \
         /home/aurelius/.bashrc \
         /home/aurelius/.taskrc \
         /home/aurelius/.tmux.conf \
         /home/aurelius/.vimrc \
      senatus:/tidepool/backup/aurelius/populus/dotfiles/

   rsync -aLKP --delete \
      -e ssh \
         /home/aurelius/.config/hre-utils \
         /home/aurelius/.config/i3 \
         /home/aurelius/.config/neomutt/ \
         /home/aurelius/.config/plover/ \
         /home/aurelius/.config/rofi \
         /home/aurelius/.config/qmk \
      senatus:/tidepool/backup/aurelius/populus/dotfiles/.config/
}


case $1 in
   -i | --internal )
      backup_internal ;;

   -s | --ssh )
      backup_ssh ;;

   *) printf "${rd}◆ ${rs}"
      printf "Select option from (${br}-i${rs})nternal (${br}-s${rs})sh\n"
      exit 1 ;;
esac
