#!/bin/bash

brightness=$1
valid=$(awk -v i="$brightness" 'BEGIN { print (0 < i && i <= 1 ? "True" : "") }')

[[ ! $valid ]] && echo -e "Invalid value. 0 < \$value <= 1" && exit 1

for monitor in $(xrandr -q | grep ' connected' | awk '{print $1}') ; do
   xrandr --output $monitor --brightness $brightness
done
