#!/bin/bash
# Currently only works for devices that have been paired/trusted.
# Pretty much just an easy shortcut for connecting to my headset.

phone="3C:28:6D:F6:22:0F"
jabra="74:5C:4B:5C:0F:01"
wraith=""

function format () {
   [[ $1 == 'red' ]]   && echo -e "\033[0;31m${2}\033[0m" && return 0
   [[ $1 == 'green' ]] && echo -e "\033[0;31m${2}\033[0m" && return 0
}

case $1 in
   'phone')  connect_to="$phone"  ;;
   'jabra')  connect_to="$jabra"  ;;
   'wraith') connect_to="$wraith" ;;
   *) format red "Specify an argument: [phone|jabra|wraith]" && exit 1
esac

found=0
while IFS= read -r line ; do
   if [[ $(echo -e "$line" | grep "$connect_to") ]] ; then
      found=1
      break
   fi
done < <(bluetoothctl --timeout 3 -- scan on)
[[ $found == 0 ]] && format red "Unable to find device." && exit 2

sudo bash -c "bluetoothctl connect '$connect_to'"
