#!/bin/bash

# 1. The prompt
# 2. Options, separate with \n
#    ^- e.g. "Quit\nCancel"
# 3. Conditional answer
# 4. Pipe to resulting script

answer=$(echo -e "$2" | dmenu -i -p "$1" -fn "Hack-Regular")

[ $answer == $3 ] && bash -c "$4" || exit 1
