#!/bin/bash
# Pretty much just a dmenu `pkill`

process=$(echo "Cancel" | dmenu -i -p "Kill which process" -fn "Hack-Regular")

# If user selects Cancel -- exit
[[ $process == "Cancel" ]] && exit 1 || \
# If user enters no process -- exit
[[ -z $process ]] && exit 1 || \
psk=$(echo -e "`ps -eo pid,comm | grep $process`" | dmenu -i -p "Confirm: " -fn "Hack-Regular")
# Else echo the associated proccesses, allow user to select the PID to kill

pid=$(echo $psk | awk '{print $1}')
sudo bash -c "kill -9 $pid"
